name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ubuntu-latest-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ubuntu-latest-
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 6.15.1
          run_install: |
            - args: []
      - name: Build
        run: yarn build
